name: Usage of Github Demo

on:
  workflow_dispatch:

jobs:

# Typically here will come the jobs that build a docker image and push it to DockerHub

  discover_evaluate_github:  
    name: Discover and Evaluate Github
    uses: scribe-public/reusable-workflows/.github/workflows/github-demo.yaml@main
    with:
        scribe_product_name: "Test-Product"
        scribe_product_version: "Some-Version"
    secrets: 
        SCRIBE_TOKEN: ${{ secrets.SCRIBE_TOKEN }}
