name: Usage of K8s Demo

on:
  push:
  workflow_dispatch:

jobs:

# Typically here will come the jobs that build a docker image and push it to DockerHub

  discover_evaluate_k8s:  
    name: Discover and Evaluate K8s
    uses: scribe-public/reusable-workflows/.github/workflows/k8s-demo.yaml@main
    with:
        scribe_product_name: "Test-Product"
        scribe_product_version: "Some-Version"
        targets: "nginx:latest"
    secrets: 
        SCRIBE_TOKEN: ${{ secrets.SCRIBE_TOKEN }}
