name: Demo usage of SSDF Policy

on:
  workflow_dispatch:

jobs:

# Typically here will come the jobs that build a docker image and push it to DockerHub

  evaluate_ssdf:  
    name: Evaluate SSDF
    uses: scribe-public/reusable-workflows/.github/workflows/k8s-demo.yaml@main
    with:
        scribe_product_name: "Test-Product"
        scribe_product_version: "Some-Version"
        targets: |
          - "busybox:latest"
          - "nginx:latest"
    secrets: 
        SCRIBE_TOKEN: ${{ secrets.SCRIBE_TOKEN }}
