name: k8s

on:
  - push
  - workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v4
      with:
        repository: medyagh/local-dev-example-with-minikube
    - name: Start minikube
      uses: medyagh/setup-minikube@latest
    - name: Try the cluster!
      run: kubectl get pods -A
    - name: Get IP
      run: | 
        echo "K8S_URL=$(kubectl cluster-info | grep 'Kubernetes control plane' | awk '{print $NF}')" >> $GITHUB_ENV
    - name: Print IP
      run: echo "${{ env.K8S_URL }}"

    - name: Create and get token
      run: |
        kubectl create secret generic my-secret --from-literal=username=myuser --from-literal=password=mypassword
        kubectl get secret my-secret -o yaml
        kubectl create serviceaccount my-serviceaccount -o yaml
        kubectl get serviceaccount my-serviceaccount
        kubectl create clusterrolebinding my-sa-admin-binding --clusterrole=cluster-admin --serviceaccount=default:my-serviceaccount
        K8S_TOKEN=$(kubectl get secret my-secret -o jsonpath='{.data.token}' | base64 --decode)
        echo "$K8S_TOKEN"
        echo "K8S_TOKEN=$K8S_TOKEN" >> $GITHUB_ENV
           
    - name: Print token
      run: echo "${{ env.K8S_TOKEN }}"
    
    - name: Discover Github
      uses: scribe-security/action-platforms@dev
      with:
        command: discover
        platform: k8s
        args: >-
              --url ${{ env.K8S_URL }}
              --token ${{ env.K8S_TOKEN }}
        #     --scope.organization *${{ github.repository_owner}}
        #     --scope.repository *${{ github.repository}}
        #     ${{ inputs.discover_args }}
            


    # - name: Build image
    #   run: |
    #     minikube image build -t local/devex:v1 .        
    # - name: Deploy to minikube
    #   run: |
    #     kubectl apply -f deploy/k8s.yaml
    #     kubectl wait --for=condition=ready pod -l app=local-devex
    # - name: Test service URLs
    #   run: |
    #     minikube service list
    #     minikube service local-devex-svc --url
    #     echo "------------------opening the service------------------"
    #     curl $(minikube service local-devex-svc --url)        


