name: k8s

on:
  - push
  - workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v4
      with:
        repository: medyagh/local-dev-example-with-minikube
    - name: Start minikube
      uses: medyagh/setup-minikube@latest
    - name: Try the cluster!
      run: | 
        kubectl version
        kubectl get pods -A
    - name: Get IP
      run: | 
        echo "K8S_URL=$(kubectl cluster-info | grep 'Kubernetes control plane' | awk '{print $NF}')" >> $GITHUB_ENV
    - name: Print IP
      run: echo "${{ env.K8S_URL }}"

    - name: Create and get token
      run: |
        set -x
        kubectl create serviceaccount my-serviceaccount -o yaml
        kubectl create clusterrole my-role \
        --verb=get --verb=watch --verb=list \
        --resource=secrets,pods,namespaces,deployments,rs.apps
        kubectl create clusterrolebinding my-sa-admin-binding --clusterrole=my-role --serviceaccount=default:my-serviceaccount
        kubectl get clusterrolebinding my-sa-admin-binding -o yaml
        K8S_TOKEN=$(kubectl create token my-serviceaccount)
        echo "K8S_TOKEN is of length: ${#K8S_TOKEN}"
        echo "First few characters of K8S_TOKEN: ${K8S_TOKEN:0:5}..."
        echo "K8S_TOKEN=$K8S_TOKEN" >> $GITHUB_ENV
           
    - name: Print token
      run: | 
        set -x
        echo "First few characters of K8S_TOKEN: ${K8S_TOKEN:0:5}..."
        echo "K8S_URL='${K8S_URL}'"
        echo "K8S_TOKEN=${K8S_TOKEN}:0:5..."
        curl -k -H "Authorization: Bearer ${K8S_TOKEN}" "${K8S_URL}/livez"

    
    - name: Discover K8S
      uses: scribe-security/action-platforms@dev
      with:
        log-level: DEBUG
        print-config: true
        command: discover
        platform: k8s
        args: >-
              --url ${{ env.K8S_URL }}
              --token ${{ env.K8S_TOKEN }}

            


    # - name: Build image
    #   run: |
    #     minikube image build -t local/devex:v1 .        
    # - name: Deploy to minikube
    #   run: |
    #     kubectl apply -f deploy/k8s.yaml
    #     kubectl wait --for=condition=ready pod -l app=local-devex
    # - name: Test service URLs
    #   run: |
    #     minikube service list
    #     minikube service local-devex-svc --url
    #     echo "------------------opening the service------------------"
    #     curl $(minikube service local-devex-svc --url)        


