name: k8s

on:
  - push
  - workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v4
      with:
        repository: medyagh/local-dev-example-with-minikube
    - name: Start minikube
      uses: medyagh/setup-minikube@latest
    - name: Try the cluster!
      run: kubectl get pods -A
    - name: Get IP
      run: | 
        echo "K8S_URL=$(kubectl cluster-info | grep 'Kubernetes control plane' | awk '{print $NF}')" >> $GITHUB_ENV
    - name: Print IP
      run: echo "${{ env.K8S_URL }}"

    - name: Create and get token
      run: |
        kubectl create secret generic my-secret --from-literal=username=myuser --from-literal=password=mypassword
        kubectl create serviceaccount my-serviceaccount
        kubectl create clusterrolebinding my-sa-admin-binding --clusterrole=cluster-admin --serviceaccount=default:my-serviceaccount
        
        # Wait for the secret to be available
        echo "Waiting for the secret to be created..."
        for i in {1..10}; do
            SECRET_NAME=$(kubectl get serviceaccount my-serviceaccount -o jsonpath='{.secrets[0].name}')
            if [ -n "$SECRET_NAME" ]; then
            break
            fi
            sleep 2
        done
        
        if [ -z "$SECRET_NAME" ]; then
            echo "Secret was not created in time."
            exit 1
        fi
        
        echo "Secret found: $SECRET_NAME"
        
        # Get the token from the secret
        K8S_TOKEN=$(kubectl get secret $SECRET_NAME -o jsonpath='{.data.token}' | base64 --decode)
        
        if [ -z "$K8S_TOKEN" ]; then
            echo "Failed to retrieve the token."
            exit 1
        fi
        
        echo "K8S_TOKEN=$K8S_TOKEN" >> $GITHUB_ENV    
    
    - name: Print token
      run: echo "${{ env.K8S_TOKEN }}"
    
    - name: Discover Github
      uses: scribe-security/action-platforms@dev
      with:
        command: discover
        platform: k8s
        args: >-
              --url ${{ env.K8S_URL }}
              --token ${{ env.K8S_TOKEN }}
        #     --scope.organization *${{ github.repository_owner}}
        #     --scope.repository *${{ github.repository}}
        #     ${{ inputs.discover_args }}
            


    # - name: Build image
    #   run: |
    #     minikube image build -t local/devex:v1 .        
    # - name: Deploy to minikube
    #   run: |
    #     kubectl apply -f deploy/k8s.yaml
    #     kubectl wait --for=condition=ready pod -l app=local-devex
    # - name: Test service URLs
    #   run: |
    #     minikube service list
    #     minikube service local-devex-svc --url
    #     echo "------------------opening the service------------------"
    #     curl $(minikube service local-devex-svc --url)        


