name: Secret Scanning

on:
  workflow_call:
    inputs:
      scribe_product_name:
        description: "Scribe Product Name"
        required: true
        type: string
      scribe_product_version:
        description: "Scribe Product Version"
        required: true
        type: string
      exit_code:
        description: "Trivy exit code"
        required: false
        default: 0
        type: number
    secrets:
        SCRIBE_TOKEN:
            description: "Scribe Token"
            required: true
        WEBHOOK_TRIGGER_SECRET:
            description: "Webhook trigger secret"
            required: false
            

jobs:
    secret-scanning:
        runs-on: ubuntu-latest
        steps:
            - name: install trivy
              run: |
                wget https://github.com/aquasecurity/trivy/releases/download/v0.55.2/trivy_0.55.2_Linux-64bit.deb
                sudo dpkg -i trivy_0.55.2_Linux-64bit.deb
                trivy -h

            - name: Checkout
              uses: actions/checkout@v2

            - name: create report name
              run: |
                REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
                echo ${{ github.ref_name}}
                echo "FILENAME=${REPO_NAME}-secret-scan.sarif" >> $GITHUB_ENV
                echo ${{ env.FILENAME }}

            - name: Run Trivy
              run: |
                trivy fs --scanners secret --severity CRITICAL,HIGH --format sarif --exit-code ${{inputs.exit_code}} -o ${{ env.FILENAME }} .

            - name: upload evidence
              uses: actions/upload-artifact@v4
              with:
                path: ${{ env.FILENAME }}
                name: secret-scan
                
            - name: install valint
              uses: scribe-security/action-installer@master

            - name: create evidence
              run: | 
                valint evidence  ${{ env.FILENAME}} --label ${{env.FILENAME}}  -P ${{ secrets.SCRIBE_TOKEN}} --product-key ${{inputs.product}} --product-version ${{inputs.version}}

            # - name: evaluate policy
            #   run: |
            #     valint verify --rule-args att_name="${{github.repository}}-secret.sarif" --policy $(pwd)/policies/sheet.yaml

            
