name: Demo usage of secret-scanning

on:
  workflow_dispatch:
  push:

jobs:

# Typically here will come the jobs that build a docker image and push it to DockerHub

  trigger:  
    name: Trigger Scribe Workflow
    uses: scribe-public/reusable-workflows/.github/workflows/secret-scanning.yaml@main
    with:
      scribe_product_name: "demo"
      scribe_product_version: "1.0.0"
    secrets: 
      SCRIBE_TOKEN: ${{ secrets.SCRIBE_DOGFOODING }}
      