name: SSDF Evaluation

on:
  workflow_call:
    # inputs:
    #   scribe_product_name:
    #     description: "Scribe Product Name"
    #     required: true
    #     type: string
    #   scribe_product_version:
    #     description: "Scribe Product Version"
    #     required: true
    #     type: string

jobs:
    secret-scanning:
        runs-on: ubuntu-latest
        steps:
            - name: install trivy
              run: |
                wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
                sudo dpkg -i trivy_0.18.3_Linux-64bit.deb
                trivy -h

            - name: Checkout
              uses: actions/checkout@v2

            - name: Run Trivy
              run: |
                trivy fs . --scanners secret --severity CRITICAL,HIGH --format sarif -o ${{github.repository}}-secret.sarif || true

            - name: upload evidence
              uses: actions/upload-artifact@v4
              with:
                path: ${{github.repository}}-secret.sarif
                
            - name: install valint
              uses: scribe-security/action-installer@dev

            - name: create evidence
              run: | 
                valint evidence  ${{github.repository}}-secret.sarif --label ${{github.repository}}-secret.sarif       

            # - name: evaluate policy
            #   run: |
            #     valint verify --rule-args att_name="${{github.repository}}-secret.sarif" --policy $(pwd)/policies/sheet.yaml

            
