name: Demo usage of secret-scanning

on:
  workflow_dispatch:
  push:

jobs:

# Typically here will come the jobs that build a docker image and push it to DockerHub

  secret-scanning:  
    name: Trigger Secret Scanning Workflow
    uses: scribe-public/reusable-workflows/.github/workflows/secret-scanning.yaml@main
    with:
      scribe_product_name: "demo"
      scribe_product_version: "1.0.0"
      exit_code: 0 # Modify if you want the check to fail before the attestation
      exclude_files: .github/workflows/secret-scanning.yaml
    secrets: 
      SCRIBE_TOKEN: ${{ secrets.SCRIBE_DOGFOODING }}
      DOGFOODING_POLICY_ACCESS: ${{ secrets.DOGFOODING_POLICY_ACCESS }}
      