name: Demo usage of SSDF Policy

on:
  workflow_dispatch:

jobs:

# Typically here will come the jobs that build a docker image and push it to DockerHub

  evaluate_ssdf:  
    name: Evaluate SSDF
    uses: scribe-public/reusable-workflows/.github/workflows/ssdf.yaml@main
    with:
        scribe_product_name: "Scribot"
        scribe_product_version: "v0.0.1-discovery-demo"
        target: "scribesecurity/heyman:latest"
    secrets: 
        SCRIBE_TOKEN: ${{ secrets.SCRIBE_TOKEN }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
