name: SSDF Evaluation

on:
  workflow_call:
    inputs:
      github_token:
        description: "GitHub Token"
        required: true
        type: string
      dockerhub_username:
        description: "DockerHub Username"
        required: true
        type: string
      dockerhub_password:
        description: "DockerHub Password"
        required: true
        type: string 
      scribe_token:
        description: "Scribe Token"
        required: true
        type: string  
      scribe_product_name:
        description: "Scribe Product Name"
        required: true
        type: string
      scribe_product_version:
        description: "Scribe Product Version"
        required: true
        type: string
      target:
        description: "Docker image for SBOM verification"
        required: true
        type: string
      policy_branch:
        description: "Policy branch for verification"
        required: false
        default: "sh-5883-ssdf"
        type: string
      discover_args:
        description: "Discovery arguments"
        required: false
        default: "--commit.skip --workflow.skip"
        type: string
      evidence_args:
        description: "Evidence arguments"
        required: false
        default: ""
        type: string

env:
    PLATFORMS_VERSION: "dev-latest"
    PLATFORMS_DB_PATH: github.platforms.db
    VALINT_SCRIBE_URL: https://api.scribesecurity.com
    VALINT_CONTEXT_TYPE: "github"
    VALINT_OUTPUT_DIRECTORY: evidence/github
    LOG_LEVEL: "INFO"
    VALINT_LOG_LEVEL: "info"
    VALINT_DISABLE_EVIDENCE_CACHE: false
    VALINT_SCRIBE_ENABLE: true 
    DOCKER_DRIVER: overlay2
    DEBUG: false

jobs:
  ssdf_evaluation:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ inputs.github_token }}
      SCRIBE_TOKEN: ${{ inputs.scribe_token }}
      DOCKERHUB_USERNAME: ${{ inputs.dockerhub_username }}
      DOCKERHUB_PASSWORD: ${{ inputs.dockerhub_password }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test variables
        run: |
            if [ -z "${{ secrets.GH_TOKEN }}" ]; then
            echo "GITHUB_TOKEN is empty or not set"
            exit 1
            else
            echo "GITHUB_TOKEN is set"
            fi

      - name: Discover Github
        uses: scribe-security/action-platforms@dev
        with:
          command: discover
          platform: github
          args: >-
            --scope.organization *${{ github.repository_owner}}
            --scope.repository *${{ github.repository}}
            ${{ inputs.discover_args }}
            

      - name: Evidence Github
        uses: scribe-security/action-platforms@dev
        with:
          command: evidence
          platform: github
          args: >-
            --organization.mapping *${{ github.repository_owner}}::${{ inputs.scribe_product_name }}::${{ inputs.scribe_product_version }}
            --repository.mapping *${{ github.repository}}::${{ inputs.scribe_product_name }}::${{ inputs.scribe_product_version }}
            ${{ inputs.evidence_args }}

      - name: Verify Github
        uses: scribe-security/action-platforms@dev
        with:
          command: verify
          platform: github
          valint_args: --valint.bundle-branch ${{ inputs.policy_branch }}
          args: >-
            --organization.mapping *${{ github.repository_owner}}::${{ inputs.scribe_product_name }}::${{ inputs.scribe_product_version }}
            --repository.mapping *${{ github.repository}}::${{ inputs.scribe_product_name }}::${{ inputs.scribe_product_version }}
            --organization.policy ssdf-org@discovery
            --org-policy-skip-aggregate
            --repository.policy ssdf-repo@discovery
            --repo-policy-skip-aggregate

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Generate SBOM for docker image
        uses: scribe-security/action-bom@master
        with:
          target: ${{ inputs.target }}
          scribe-enable: true
          product-key:  ${{ inputs.scribe_product_name }}
          product-version: ${{ inputs.scribe_product_version }}
          scribe-client-secret: ${{ secrets.SCRIBE_TOKEN }}

      - name: Verify SBOM
        uses: scribe-security/action-verify@master
        with:
          target: ${{ inputs.target }}
          scribe-enable: true
          product-key:  ${{ inputs.scribe_product_name }}
          product-version: ${{ inputs.scribe_product_version }}
          scribe-client-secret: ${{ secrets.SCRIBE_TOKEN }}
          bundle-branch: ${{ inputs.policy_branch }}
          policy: ssdf-image@discovery
