name: Trigger Scribe Workflow

on:
  workflow_call:
    inputs:
      product:
        description: "Scribe Product Name"
        required: true
        type: string
      version:
        description: "Scribe Product Version"
        required: true
        type: string
      github_org:
        description: "GitHub organization"
        required: true
        type: string
      github_repo:
        description: "GitHub repository"
        required: true
        type: string
      event_type:
        description: "Event type"
        required: true
        type: string

    secrets:
        WEBHOOK_SECRET:
            description: "Webhook secret"
            required: true

jobs:
    trigger_workflow:
        runs-on: ubuntu-latest
        steps:
            - name: Send webhook to Repository A
              env:
                WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
              run: |
                echo "${{ toJson(github.event) }}" > EVENT_PAYLOAD
                echo "EVENT_DATA=$(cat EVENT_PAYLOAD)" >> $GITHUB_ENV
                curl -X POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer $WEBHOOK_SECRET" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/${{inputs.github_org}}/${{inputs.github_repo}}/dispatches \
                  -d '{"event_type": "${{inputs.event_type}}", "client_payload": { "product": "${{inputs.product}}" \ 
                      "version": "${{inputs.version}}", "original_event":"${{env.EVENT_PAYLOAD}}" }}'

