name: Demo usage of trigger.yaml reusable workflow

on:
  workflow_dispatch:
#  push:

jobs:

# Typically here will come the jobs that build a docker image and push it to DockerHub

  trigger:  
    name: Trigger Scribe Workflow
    uses: scribe-public/reusable-workflows/.github/workflows/trigger.yaml@main
    with:
        product: "sample-policies"
        version: "reuable-vars"
        event_type: "sample-policies-release"
        workflow_github_org: scribe-security
        workflow_github_repo: dogfooding
    secrets: 
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
