name: Trigger Webhook

on:
  workflow_dispatch:

jobs:
  trigger_webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Send webhook to Repository A
      env:
        REPO_A_TOKEN: ${{ secrets.WEBHOOK_SECRET }}
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $REPO_A_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/scribe-security/dogfooding/dispatches \
          -d '{"event_type": "custom-event", "client_payload": { "data": "Important information from reusable-workflows" }}'

    - name: Send webhook to Repository A specifying a workflow to run
      env:
        REPO_A_TOKEN: ${{ secrets.WEBHOOK_SECRET }}
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $REPO_A_TOKEN" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/scribe-security/dogfooding/actions/workflows/trigerred.yaml/dispatches \
        -d '{"ref":"main","inputs":{ "data": "Workflow dispatch blah blah blah"}}'